// Code generated by protoc-gen-go. DO NOT EDIT.
// source: status.proto

/*
Package qw is a generated protocol buffer package.

It is generated from these files:
	status.proto

It has these top-level messages:
	Status
*/
package qw

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Status struct {
	JobId    uint32 `protobuf:"varint,1,opt,name=job_id,json=jobId" json:"job_id,omitempty"`
	Progress uint32 `protobuf:"varint,2,opt,name=progress" json:"progress,omitempty"`
	Error    string `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
}

func (m *Status) Reset()                    { *m = Status{} }
func (m *Status) String() string            { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()               {}
func (*Status) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Status) GetJobId() uint32 {
	if m != nil {
		return m.JobId
	}
	return 0
}

func (m *Status) GetProgress() uint32 {
	if m != nil {
		return m.Progress
	}
	return 0
}

func (m *Status) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*Status)(nil), "qw.status")
}

func init() { proto.RegisterFile("status.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 108 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x2e, 0x49, 0x2c,
	0x29, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x2c, 0x57, 0x0a, 0xe4, 0x62,
	0x83, 0x88, 0x09, 0x89, 0x72, 0xb1, 0x65, 0xe5, 0x27, 0xc5, 0x67, 0xa6, 0x48, 0x30, 0x2a, 0x30,
	0x6a, 0xf0, 0x06, 0xb1, 0x02, 0x79, 0x9e, 0x29, 0x42, 0x52, 0x5c, 0x1c, 0x40, 0xd5, 0xe9, 0x45,
	0xa9, 0xc5, 0xc5, 0x12, 0x4c, 0x60, 0x09, 0x38, 0x5f, 0x48, 0x84, 0x8b, 0x35, 0xb5, 0xa8, 0x28,
	0xbf, 0x48, 0x82, 0x19, 0x28, 0xc1, 0x19, 0x04, 0xe1, 0x24, 0xb1, 0x81, 0x4d, 0x37, 0x06, 0x04,
	0x00, 0x00, 0xff, 0xff, 0x09, 0xf8, 0x31, 0x7b, 0x6d, 0x00, 0x00, 0x00,
}
