#!/bin/bash

export LINOTTE_TAXREF_SERVICE_ENDPOINT=":50052"
export LINOTTE_TAXREF_DATABASE_HOST="localhost"
export LINOTTE_TAXREF_DATABASE_USER="linotte"
export LINOTTE_TAXREF_DATABASE_PASSWORD="l1n0tt3passwd"
export LINOTTE_TAXREF_DATABASE_NAME="linotte"
export LINOTTE_TAXREF_DATABASE_PORT=3306
export LINOTTE_TAXREF_DATABASE_VERBOSE_MODE="false"

make && go build && ./taxref
