#!/bin/bash

export LINOTTE_PROTECTION_SERVICE_ENDPOINT=":50056"
export LINOTTE_PROTECTION_DATABASE_HOST="localhost"
export LINOTTE_PROTECTION_DATABASE_USER="linotte"
export LINOTTE_PROTECTION_DATABASE_PASSWORD="l1n0tt3passwd"
export LINOTTE_PROTECTION_DATABASE_NAME="linotte"
export LINOTTE_PROTECTION_DATABASE_PORT=3306
export LINOTTE_PROTECTION_DATABASE_VERBOSE_MODE="false"

make && go build && ./protection
